---
kind: pipeline
type: docker
name: docker-grobid

steps:
- name: build_test_image
  image: plugins/docker
  settings:
    username:
      from_secret: canister_username
    password:
      from_secret: canister_password
    repo: chazu/docker-grobid
